apiVersion: apps/v1
kind: Deployment
metadata:
  name: noodle-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noodle-dispatcher
  template:
    metadata:
      labels:
        app: noodle-dispatcher
    spec:
      containers:
      - name: noodle-dispatcher
        image: noodle-dispatcher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: noodle-dispatcher
spec:
  selector:
    app: noodle-dispatcher
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: 30080
  type: NodePort